[buildPlans.BuddyMono]
family = "Buddy Mono"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.BuddyMono.variants.design]
one = "no-base"
two = "curly-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "straight-serifless"
eight = "crossing"
nine = "open-contour"
zero = "slashed"
capital-a = "straight-serifless"
capital-b = "standard-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "standing-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-flat-top-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "single-storey-serifless"
b = "toothed-serifless"
c = "bilateral-inward-serifed"
d = "toothed-serifless"
e = "rounded-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-serifless"
h = "straight-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-serifless"
s = "serifless"
t = "flat-hook-asymmetric-short-neck2"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless"
lower-theta = "oval"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
tilde = "low"
asterisk = "penta-mid"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "slanted"
ampersand = "closed"
at = "threefold"
dollar = "through"
cent = "through-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
question = "corner"
pilcrow = "high"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "middle"

[buildPlans.BuddyMono.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.BuddyMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.BuddyMono.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.BuddyMono.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.BuddyMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.BuddyMono.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.BuddyMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.BuddyMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.BuddyMono.slopes.Italic]
angle = 11.8
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.BuddyMono.metricOverride]
xHeight = 540
cap = 700
ascender = 750
sb = 80

accentWidth = 182
accentClearance = 76
accentHeight = 162
accentStackOffset = 208

leading = 1400
parenSize = 860
dotSize = 'blend(weight, [100, 110], [400, 125], [900, 150])'
periodSize = 140

essRatio = 1.03
essRatioUpper = 1.03
essRatioLower = 1.03
essRatioQuestion = 1.03
archDepth = 152
smallArchDepth = 157

